repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.28.0
    hooks:
      - id: eslint
        args: ["--ext", ".ts,.tsx"]
        types: [ts, tsx]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]
        types: [ts, tsx]
