import { User } from "firebase/auth";
import { Timestamp } from "firebase/firestore";

export type UserType = {
  id: string; //auto generated by firebase
  name: string;
  email: string;
  createdAt: Timestamp;
  photoURL?: string; // Optional property for user's profile picture
  bio?: string; // Optional property for user's bio
  followersCount?: number; // Optional property for followers count
  followingCount?: number; // Optional property for following count
  postsCount?: number; // Optional property for posts count
};

export class UserModel {
  id: string; //auto generated by firebase
  name: string;
  email: string;
  createdAt: Timestamp;
  photoURL?: string; // Optional property for user's profile picture
  bio?: string; // Optional property for user's bio
  followersCount?: number; // Optional property for followers count
  followingCount?: number; // Optional property for following count
  postsCount?: number; // Optional property for posts count

  constructor(
    id: string,
    name: string | null,
    email: string | null,
    photoURL?: string | null,
    bio?: string,
    followersCount?: number,
    followingCount?: number,
    postsCount?: number,
  ) {
    this.id = id;
    this.name = name || "";
    this.email = email || "";
    this.photoURL = photoURL || "";
    this.bio = bio;
    this.followersCount = followersCount;
    this.followingCount = followingCount;
    this.postsCount = postsCount;
    this.createdAt = Timestamp.now();
  }
}

export const convertFirebaseUserToUserModel = async (user: User) => {
  const userModel = new UserModel(
    user.uid,
    user.displayName,
    user.email,
    user.photoURL,
  );
  return JSON.parse(JSON.stringify(userModel));
};
