import { UserMetadata } from "firebase/auth";
interface ProfileStats {
  followersCount?: number;
  followingCount?: number;
  postsCount?: number;
}
interface Biometrics {
  weight: number;
  height: number;
}
export type ProfileForm = {
  displayName: string;
  biometrics: Biometrics;
  // shoeModel: string;
};

export interface AppUser {
  readonly uid: string; //auto generated by firebase
  displayName: string;
  email: string;
  emailVerified: boolean;
  isAnonymous: boolean;
  phoneNumber?: string;
  photoURL?: string; // Optional property for user's profile picture
  stats: ProfileStats;
  biometrics: Biometrics;
  readonly metadata: UserMetadata;
  toJSON(): object;
}
export function createAppUserFromJSON(json: any): AppUser {
  if (!json || typeof json !== "object") {
    throw new Error("Invalid JSON object");
  }

  return {
    uid: json.uid,
    displayName: json.displayName,
    email: json.email,
    emailVerified: json.emailVerified,
    isAnonymous: json.isAnonymous,
    phoneNumber: json.phoneNumber ?? null,
    photoURL: json.photoURL ?? null,

    biometrics: {
      weight: json.biometrics?.weight ?? 0,
      height: json.biometrics?.height ?? 0,
    },

    stats: {
      followersCount: json.stats?.followersCount ?? 0,
      followingCount: json.stats?.followingCount ?? 0,
      postsCount: json.stats?.postsCount ?? 0,
    },

    metadata: json.metadata as UserMetadata,

    toJSON() {
      return {
        uid: this.uid,
        displayName: this.displayName,
        email: this.email,
        emailVerified: this.emailVerified,
        isAnonymous: this.isAnonymous,
        phoneNumber: this.phoneNumber,
        photoURL: this.photoURL,
        stats: this.stats,
        biometrics: this.biometrics,
        metadata: this.metadata,
      };
    },
  };
}
